export enum unlockedGames {
  "Sqeek & Sausage" = "Sqeek & Sausage",
  "The Nautilus' Traps" = "The Nautilus' Traps",
  "The House on the Hill" = "The House on the Hill",
  // "The Island of Doctor Goose",
  // "The Formula",
  // "The Tonipal's Treasure",
  // "A Noside Story",
  // "Tombstone Express",
  // "The Adventures of Oz",
  // "Insert Coin",
  // "In Pursuit of the White Rabbit",
  // "Sherlock Holmes - The Scarlet Tread of Murder",
  // "The Noside Show",
  // "Arsène Lupin and the Great White Diamond",
  // "Lost In the Time Warp",
  // "The Night Of The Boogeyman",
  // "Expedition Challenger",
  // "Scheherazade’s Last Tale",
  // "The Seventh Screening",
  // "The Dragon's Seven Tests",
  // "Mission #07",
  // "Rebels",
  // "Smugglers",
  // "Imperial Agents",
  // "Around the World in Eighty Days",
  // "Greed Mythology",
  // "A Noside story sequel"
};